apiVersion: batch/v1
kind: CronJob
metadata:
  name: busybox-cronjob
  namespace: flux
spec:
  schedule: '*/5 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: busybox
              image: busybox
              args:
                - /bin/sh
                - '-c'
                - date; echo Hello from the Kubernetes cluster!!!!
          restartPolicy: OnFailure