apiVersion: batch/v1
kind: CronJob
metadata:
  name: busybox-cronjob
  namespace: ops
spec:
  schedule: "*/5 * * * *"  # This schedule runs the job every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
