apiVersion: batch/v1
kind: CronJob
metadata:
  name: busybox-cronjob
spec:
  # The schedule is in Cron format, "*/1 * * * *" means "every minute".
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
            # Command to print the current date and time
            command: ["/bin/sh", "-c", "date; echo Hello from the Kubernetes cluster"]
          restartPolicy: OnFailure